### ISSUE TITLE
Failed to load a language-html package grammar

### ISSUE THREAD

**Issue by kamrannnnn** [atom/language-html#207]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [language-html](https://github.com/atom/language-html) package 0.51.1

### Stack Trace

Failed to load a language-html package grammar

```
At Cannot find module 'tree-sitter-embedded-template' in C:\Users\kamran\.atom\packages\language-html-master\grammars\tree-sitter-ejs.cson

Error: Cannot find module 'tree-sitter-embedded-template'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.28.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.28.2/resources/app/src/module-cache.js:354:58)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.28.2/resources/app/src/tree-sitter-grammar.js:43:51)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.28.2/resources/app/src/grammar-registry.js:494:20)
    at CSON.readFile (~/AppData/Local/atom/app-1.28.2/resources/app/src/grammar-registry.js:476:35)
    at parseContents (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/season/lib/cson.js:123:13)
    at ~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/season/lib/cson.js:226:30
    at FSReqWrap.oncomplete (fs.js:152:21)
  at /packages/language-html-master/grammars/tree-sitter-ejs.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
> Thrown From: language-html package 0.51.1

Looks like you've tried to manually install language-html (Atom 1.28.2 uses language-html 0.49.1) but maybe didn't successfully `apm install` first?  Are you intentionally trying to run 0.51.1 for a particular reason?

**Comment by dougc84** [comment]
Seeing this issue again on 1.40.1 x64 for macOS.
